---
- name: Get saved SSH pubkeys for {{ user_username }}
  uri:
    url: "{{ api_base_url }}/users/{{ user_id }}/keys"
    headers:
      "{{ common_admin_headers }}"
    status_code: [200]
  register: get_saved_ssh_pubkeys

- name: Set saved_pubkeys fact
  set_fact:
    saved_pubkeys: "{{ get_saved_ssh_pubkeys.json }}"

- name: Ensure temp dir {{ tmp_dir }}
  file:
    path: "{{ tmp_dir }}"
    state: directory

- name: Get desired pubkeys from {{ desired_ssh_pubkeys_url }}
  get_url:
    url: "{{ desired_ssh_pubkeys_url }}"
    dest: "{{ tmp_dir }}/{{ user_username }}-desired_ssh_pubkeys"

- name: Add SSH pubkey
  with_lines: cat {{ tmp_dir }}/{{ user_username }}-desired_ssh_pubkeys
  loop_control:
    loop_var: desired_ssh_pubkey
  when: desired_ssh_pubkey not in (saved_pubkeys | map(attribute='key') | list | join)
  changed_when: true
  uri:
    url: "{{ api_base_url }}/users/{{ user_id }}/keys"
    method: POST
    headers:
      "{{ common_admin_headers }}"
    body: >-
      title=Managed By Relaxdiego CICD&
      key={{ desired_ssh_pubkey | urlencode }}
    status_code: [200, 201]
