---
- name: Validate API access
  become: false
  delegate_to: 127.0.0.1
  uri:
    url: "{{ gitlab_external_url }}/api/v4/projects"
    headers:
      PRIVATE-TOKEN: "{{ gitlab_root_api_token }}"
    status_code: [200]
  changed_when: false

- name: Validate SMTP
  command: gitlab-rails runner -e production "Notify.test_email('{{ gitlab_email_from }}', 'SMTP Test From {{ gitlab_external_url }}', 'It Works!').deliver_now"
  when: gitlab_configuration.changed
  changed_when: false
