---
# This playbook is used to pre-bake images created by the local-cluster
# builder in builder/template.json. If you want to add pre-baking tasks
# that should apply to all builders, please add those to
# configurator/pre-bake-common.yml instead.

# Make sure to run this playbook with `--tags=prebake` so that the gitlab
# role will only execute the tasks tagged with prebake.

- import_playbook: pre-bake-common.yml

- name: Local Cluster Image Pre-baking Tasks
  gather_facts: false
  hosts: all
  become: true

  roles:
    - gitlab
